# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(338, 379)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BarBase = QtWidgets.QFrame(self.centralwidget)
        self.BarBase.setGeometry(QtCore.QRect(10, 10, 330, 330))
        self.BarBase.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BarBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BarBase.setObjectName("BarBase")
        self.progress = QtWidgets.QFrame(self.BarBase)
        self.progress.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.progress.setStyleSheet("QFrame{\n"
"    border-radius: 150px;\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.999 rgba(255, 0, 127, 0), stop:1 rgba(85, 170, 255, 255));\n"
"}")
        self.progress.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progress.setObjectName("progress")
        self.fext = QtWidgets.QFrame(self.BarBase)
        self.fext.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.fext.setStyleSheet("QFrame{\n"
"    border-radius: 150px;\n"
"    background-color: rgb(50, 50, 150);\n"
"}")
        self.fext.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fext.setObjectName("fext")
        self.fint = QtWidgets.QFrame(self.BarBase)
        self.fint.setGeometry(QtCore.QRect(25, 25, 270, 270))
        self.fint.setStyleSheet("QFrame{\n"
"    border-radius: 135px;\n"
"    background-color: rgb(0, 0, 100);\n"
"}")
        self.fint.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fint.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fint.setObjectName("fint")
        self.label = QtWidgets.QLabel(self.fint)
        self.label.setGeometry(QtCore.QRect(50, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"color: #FFFFFF;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pause = QtWidgets.QPushButton(self.fint)
        self.pause.setGeometry(QtCore.QRect(170, 130, 40, 40))
        self.pause.setAutoFillBackground(False)
        self.pause.setStyleSheet("QFrame{\n"
"    border-radius: 20px;\n"
"    background-color: rgb(0,255,255);\n"
"}")
        self.pause.setObjectName("pause")
        self.start = QtWidgets.QPushButton(self.fint)
        self.start.setGeometry(QtCore.QRect(60, 130, 40, 40))
        self.start.setObjectName("start")
        self.reset = QtWidgets.QPushButton(self.fint)
        self.reset.setGeometry(QtCore.QRect(115, 190, 40, 40))
        self.reset.setObjectName("reset")
        self.fext.raise_()
        self.progress.raise_()
        self.fint.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 338, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "00:00"))
        self.pause.setText(_translate("MainWindow", "ll"))
        self.start.setText(_translate("MainWindow", "D"))
        self.reset.setText(_translate("MainWindow", "O"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
